// inertia/pages/manage/papers/show.tsx
import { InferPageProps } from '@adonisjs/inertia/types'
import { Link } from '@inertiajs/react'
import { Button } from '~/components/ui/button'
import type { PapersController } from '../../../app/controllers/manage/papers_controller'

type Props = InferPageProps<typeof PapersController, 'show'>

export default function ShowPaper({ paper }: Props) {
  const mcqQuestions = paper.questions.filter(q => q.type === 'mcq')
  const saqQuestions = paper.questions.filter(q => q.type === 'saq')

  return (
    <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      {/* Paper Header with Actions */}
      <div className="mb-8 flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">{paper.title}</h1>
          <div className="mt-2 flex items-center text-sm text-gray-500">
            <span>{paper.concept.title}</span>
            <span className="mx-2">&bull;</span>
            <span>{paper.year}</span>
            <span className="mx-2">&bull;</span>
            <span>{paper.exam_type}</span>
          </div>
        </div>
        <div className="flex gap-2">
          <Link href={`/manage/papers/${paper.slug}/questions/new?type=mcq`}>
            <Button variant="outline">Add MCQ</Button>
          </Link>
          <Link href={`/manage/papers/${paper.slug}/questions/new?type=saq`}>
            <Button variant="outline">Add SAQ</Button>
          </Link>
        </div>
      </div>

      {/* MCQ Section */}
      {mcqQuestions.length > 0 && (
        <div className="mb-8">
          <h2 className="text-xl font-semibold mb-4">
            Multiple Choice Questions ({mcqQuestions.length})
          </h2>
          <div className="space-y-6">
            {mcqQuestions.map((question, index) => (
              <div key={question.id} className="group bg-white shadow rounded-lg p-6">
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-start">
                      <span className="font-medium mr-4">{index + 1}.</span>
                      <div>
                        <p className="text-gray-900 mb-4">{question.question_text}</p>
                        <div className="ml-4 space-y-2">
                          {question.choices?.map((choice) => (
                            <div
                              key={choice.id}
                              className={`p-3 rounded-lg ${
                                choice.is_correct ? 'bg-green-50 border border-green-200' : 'bg-gray-50'
                              }`}
                            >
                              <p className="text-gray-900">{choice.choice_text}</p>
                              {choice.is_correct && (
                                <p className="text-sm text-green-600 mt-1">{choice.explanation}</p>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="opacity-0 group-hover:opacity-100 transition-opacity flex gap-2">
                    <Link href={`/manage/papers/${paper.slug}/questions/${question.slug}/edit`}>
                      <Button variant="outline" size="sm">Edit</Button>
                    </Link>
                    <form 
                      action={`/manage/papers/${paper.slug}/questions/${question.slug}`} 
                      method="DELETE"
                    >
                      <Button 
                        variant="destructive" 
                        size="sm"
                        type="submit"
                        onClick={(e) => {
                          e.preventDefault()
                          if (confirm('Remove this question?')) {
                            e.currentTarget.form?.submit()
                          }
                        }}
                      >
                        Remove
                      </Button>
                    </form>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SAQ Section */}
      {saqQuestions.length > 0 && (
        <div>
          <h2 className="text-xl font-semibold mb-4">
            Structured Questions ({saqQuestions.length})
          </h2>
          <div className="space-y-6">
            {saqQuestions.map((question, index) => (
              <div key={question.id} className="group bg-white shadow rounded-lg p-6">
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-start">
                      <span className="font-medium mr-4">{index + 1}.</span>
                      <div>
                        <p className="text-gray-900 mb-4">{question.question_text}</p>
                        <div className="ml-4 space-y-4">
                          {question.parts?.map((part, partIndex) => (
                            <div key={part.id} className="border-l-2 border-gray-200 pl-4">
                              <p className="text-gray-900 font-medium mb-2">
                                {String.fromCharCode(97 + partIndex)}) {part.part_text}
                              </p>
                              <p className="text-sm text-gray-500">
                                Expected: {part.expected_answer}
                              </p>
                              <p className="text-sm text-gray-500">
                                Marks: {part.marks}
                              </p>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="opacity-0 group-hover:opacity-100 transition-opacity flex gap-2">
                    <Link href={`/manage/papers/${paper.slug}/questions/${question.slug}/edit`}>
                      <Button variant="outline" size="sm">Edit</Button>
                    </Link>
                    <form 
                      action={`/manage/papers/${paper.slug}/questions/${question.slug}`} 
                      method="DELETE"
                    >
                      <Button 
                        variant="destructive" 
                        size="sm"
                        type="submit"
                        onClick={(e) => {
                          e.preventDefault()
                          if (confirm('Remove this question?')) {
                            e.currentTarget.form?.submit()
                          }
                        }}
                      >
                        Remove
                      </Button>
                    </form>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// inertia/pages/manage/concepts/show.vue
<script setup lang="ts">
import { Link, useForm } from '@inertiajs/vue3'
import type ConceptDto from '#dtos/concept'
import type QuestionDto from '#dtos/question'
import { computed, ref, watchEffect } from 'vue'
import AdminLayout from '~/layouts/AdminLayout.vue'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '~/components/ui/dialog'

defineOptions({ layout: AdminLayout })

const props = defineProps<{
  concept: ConceptDto
  children: ConceptDto[]
  questions: QuestionDto[]
  content: string | null
}>()

const children = ref(props.children)
const questions = ref(props.questions)
const content = computed(() => props.content || '')

watchEffect(() => {
  children.value = props.children
  questions.value = props.questions
})

const showEditDialog = ref(false)

const form = useForm({
  title: props.concept.title,
  knowledgeBlock: props.content || '',
  isTerminal: props.concept.isTerminal,
})

const handleSubmit = () => {
  form.put(`/manage/concepts/${props.concept.slug}`, {
    onSuccess: () => {
      showEditDialog.value = false
    },
  })
}

const handleDelete = () => {
  if (confirm('Are you sure you want to delete this concept?')) {
    form.delete(`/manage/concepts/${props.concept.slug}`)
  }
}
</script>

<template>
  <div class="container mx-auto px-4 py-8">
    <nav class="flex items-center gap-2 mb-6 text-sm">
      <Link href="/manage/concepts">Concepts</Link>
      <span>/</span>
      <span>{{ concept.title }}</span>
    </nav>

    <div class="space-y-8">
      <div class="flex items-center justify-between">
        <h1 class="text-3xl font-bold">{{ concept.title }}</h1>
        <div class="flex gap-2">
          <Button variant="outline" @click="showEditDialog = true"> Edit </Button>
          <Button variant="destructive" @click="handleDelete"> Delete </Button>
        </div>
      </div>

      <!-- Child Concepts Grid -->
      <div v-if="children?.length" class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Link
          v-for="child in children"
          :key="child.id"
          :href="`/manage/concepts/${child.slug}`"
          class="p-4 rounded-lg border hover:border-primary transition-colors"
        >
          <h3 class="text-lg font-semibold">{{ child.title }}</h3>
        </Link>
      </div>

      <Dialog :open="showEditDialog" @update:open="showEditDialog = $event">
        <DialogContent class="sm:max-w-[800px]">
          <DialogHeader>
            <DialogTitle>Edit Concept</DialogTitle>
          </DialogHeader>

          <form @submit.prevent="handleSubmit" class="space-y-4">
            <div class="space-y-2">
              <Label>Title</Label>
              <Input v-model="form.title" />
              <p v-if="form.errors.title" class="text-sm text-destructive">
                {{ form.errors.title }}
              </p>
            </div>

            <!-- <div v-if="concept.isTerminal" class="space-y-2">
              <Label>Content</Label>
              <Textarea v-model="form.knowledgeBlock" rows="10" />
            </div> -->

            <Button type="submit" :disabled="form.processing">
              {{ form.processing ? 'Saving...' : 'Save Changes' }}
            </Button>
          </form>
        </DialogContent>
      </Dialog>

      <!-- Content -->
      <div v-if="content" class="prose max-w-none" v-html="content" />

      <!-- Questions -->
      <div v-if="questions?.length" class="mt-8 space-y-8">
        <h2 class="text-2xl font-bold">Practice Questions</h2>
        <div v-for="question in questions" :key="question.id" class="space-y-4">
          <div class="p-4 rounded-lg border">
            <p class="font-medium">{{ question.questionText }}</p>

            <!-- MCQ Choices -->
            <div v-if="question.choices?.length" class="mt-4 space-y-2">
              <div
                v-for="choice in question.choices"
                :key="choice.id"
                class="flex items-start gap-2"
              >
                <span>{{ choice.choiceText }}</span>
              </div>
            </div>

            <!-- SAQ Parts -->
            <!-- SAQ Parts -->
            <div v-if="question.parts?.length" class="mt-4 space-y-4">
              <div v-for="part in question.parts" :key="part.id" class="border-l-2 pl-4">
                <p class="font-medium">{{ part.partText }}</p>
                <p class="font-medium">{{ part.expectedAnswer }}</p>
                <p class="text-sm text-muted-foreground mt-2">Marks: {{ part.marks }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
