// inertia/pages/concepts/show.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3'
import type ConceptDto from '#dtos/concept'
import type QuestionDto from '#dtos/question'
import { computed, ref, watchEffect } from 'vue'

const props = defineProps<{
    concept: ConceptDto
    children: ConceptDto[]
    questions: QuestionDto[]
    content: string | null
}>()

const children = ref(props.children)
const questions = ref(props.questions)
const content = computed(() => props.content || '')

watchEffect(() => {
    children.value = props.children
    questions.value = props.questions
})
</script>

<template>
    <div class="container mx-auto px-4 py-8">
        <nav class="flex items-center gap-2 mb-6 text-sm">
            <Link href="/concepts">Concepts</Link>
            <span>/</span>
            <span>{{ concept.title }}</span>
        </nav>

        <div class="space-y-8">
            <div>
                <h1 class="text-3xl font-bold">{{ concept.title }}</h1>
            </div>

            <!-- Child Concepts Grid -->
            <div v-if="children?.length" class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                <Link v-for="child in children" :key="child.id" :href="`/concepts/${child.slug}`"
                    class="p-4 rounded-lg border hover:border-primary transition-colors">
                <h3 class="text-lg font-semibold">{{ child.title }}</h3>
                </Link>
            </div>

            <!-- Content -->
            <div v-if="content" class="prose max-w-none" v-html="content" />

            <!-- Questions -->
            <div v-if="questions?.length" class="mt-8 space-y-8">
                <h2 class="text-2xl font-bold">Practice Questions</h2>
                <div v-for="question in questions" :key="question.id" class="space-y-4">
                    <div class="p-4 rounded-lg border">
                        <p class="font-medium">{{ question.questionText }}</p>

                        <!-- MCQ Choices -->
                        <div v-if="question.choices?.length" class="mt-4 space-y-2">
                            <div v-for="choice in question.choices" :key="choice.id" class="flex items-start gap-2">
                                <span>{{ choice.choiceText }}</span>
                            </div>
                        </div>

                        <!-- SAQ Parts -->
                        <!-- SAQ Parts -->
                        <div v-if="question.parts?.length" class="mt-4 space-y-4">
                            <div v-for="part in question.parts" :key="part.id" class="border-l-2 pl-4">
                                <p class="font-medium">{{ part.partText }}</p>
                                <p class="font-medium">{{ part.expectedAnswer }}</p>
                                <p class="text-sm text-muted-foreground mt-2">
                                    Marks: {{ part.marks }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// inertia/pages/papers/show.tsx
import { InferPageProps } from '@adonisjs/inertia/types'
import { Link } from '@inertiajs/react'
import type { IndexController } from '../../../app/controllers/papers/index_controller'

type Props = InferPageProps<typeof IndexController, 'show'>

export default function ShowPaper({ paper }: Props) {
  const mcqQuestions = paper.questions.filter(q => q.type === 'mcq')
  const saqQuestions = paper.questions.filter(q => q.type === 'saq')

  return (
    <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      {/* Paper Header */}
      <div className="mb-8">
        <Link 
          href="/papers" 
          className="text-sm text-gray-500 hover:text-gray-700 mb-4 inline-block"
        >
          ← Back to Papers
        </Link>
        <h1 className="text-2xl font-bold text-gray-900">{paper.title}</h1>
        <div className="mt-2 flex items-center text-sm text-gray-500">
          <span>{paper.concept.title}</span>
          <span className="mx-2">&bull;</span>
          <span>{paper.year}</span>
          <span className="mx-2">&bull;</span>
          <span>{paper.examType}</span>
        </div>
      </div>

      {/* Questions */}
      <div className="space-y-8">
        {mcqQuestions.length > 0 && (
          <div>
            <h2 className="text-xl font-semibold mb-4">Multiple Choice Questions</h2>
            <div className="space-y-6">
              {mcqQuestions.map((question, index) => (
                <div key={question.id} className="bg-white shadow rounded-lg p-6">
                  <div className="flex items-start">
                    <span className="font-medium mr-4">{index + 1}.</span>
                    <div>
                      <p className="text-gray-900 mb-4">{question.questionText}</p>
                      <div className="ml-4 space-y-2">
                        {question.choices?.map((choice) => (
                          <div
                            key={choice.id}
                            className={`p-3 rounded-lg ${
                              choice.isCorrect ? 'bg-green-50 border border-green-200' : 'bg-gray-50'
                            }`}
                          >
                            <p className="text-gray-900">{choice.text}</p>
                            {choice.isCorrect && (
                              <p className="text-sm text-green-600 mt-1">{choice.explanation}</p>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {saqQuestions.length > 0 && (
          <div>
            <h2 className="text-xl font-semibold mb-4">Structured Questions</h2>
            <div className="space-y-6">
              {saqQuestions.map((question, index) => (
                <div key={question.id} className="bg-white shadow rounded-lg p-6">
                  <div className="flex items-start">
                    <span className="font-medium mr-4">{index + 1}.</span>
                    <div>
                      <p className="text-gray-900 mb-4">{question.questionText}</p>
                      <div className="ml-4 space-y-4">
                        {question.parts?.map((part, partIndex) => (
                          <div key={part.id} className="border-l-2 border-gray-200 pl-4">
                            <p className="text-gray-900 font-medium mb-2">
                              {String.fromCharCode(97 + partIndex)}) {part.text}
                            </p>
                            <p className="text-sm text-gray-500">
                              Expected: {part.expectedAnswer}
                            </p>
                            <p className="text-sm text-gray-500">
                              Marks: {part.marks}
                            </p>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
