// inertia/pages/manage/papers/index.tsx
import { InferPageProps } from '@adonisjs/inertia/types'
import { Link } from '@inertiajs/react'
import { Button } from '~/components/ui/button'
import type { PapersController } from '../../../app/controllers/manage/papers_controller'

type Props = InferPageProps<typeof ManagePapersController, 'index'>

export default function ManagePapersList({ papersByConcept }: Props) {
  return (
    <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <div className="px-4 py-6 sm:px-0">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-semibold text-gray-900">Manage Papers</h1>
          <Link href="/manage/papers/create">
            <Button>Add New Paper</Button>
          </Link>
        </div>
        
        <div className="mt-6 space-y-8">
          {Object.entries(papersByConcept).map(([conceptTitle, papers]) => (
            <div key={conceptTitle} className="bg-white shadow rounded-lg overflow-hidden">
              <div className="px-4 py-3 bg-gray-50 border-b border-gray-200">
                <h2 className="text-lg font-medium text-gray-900">
                  {conceptTitle} ({papers.length})
                </h2>
              </div>
              <ul className="divide-y divide-gray-200">
                {papers.map((paper) => (
                  <li key={paper.id} className="p-4 hover:bg-gray-50">
                    <div className="flex items-center justify-between">
                      <Link 
                        href={`/manage/papers/${paper.slug}`} 
                        className="flex-1"
                      >
                        <h3 className="text-lg font-medium">{paper.title}</h3>
                        <div className="mt-1 flex items-center text-sm text-gray-500">
                          <span>{paper.year}</span>
                          <span className="mx-2">&bull;</span>
                          <span>{paper.examType}</span>
                          <span className="mx-2">&bull;</span>
                          <span>{paper.questions.length} Questions</span>
                        </div>
                      </Link>
                      <div className="flex gap-2">
                        <Link href={`/manage/papers/${paper.slug}/edit`}>
                          <Button variant="outline" size="sm">Edit</Button>
                        </Link>
                        <Button 
                          variant="destructive" 
                          size="sm"
                          onClick={() => {
                            if (confirm('Delete this paper?')) {
                              // Delete action
                            }
                          }}
                        >
                          Delete
                        </Button>
                      </div>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// export default function PapersList({ papersByConcept }: Props) {
//   return (
//     <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
//       <div className="px-4 py-6 sm:px-0">
//         <div className="flex justify-between items-center mb-6">
//           <h1 className="text-2xl font-semibold text-gray-900">Past Papers</h1>
//           <Link href="/manage/papers/create">
//             <Button>Add New Paper</Button>
//           </Link>
//         </div>
        
//         <div className="mt-6 space-y-8">
//           {Object.entries(papersByConcept).map(([conceptTitle, conceptPapers]) => (
//             <div key={conceptTitle} className="bg-white shadow overflow-hidden rounded-md">
//               <div className="px-4 py-3 bg-gray-50 border-b border-gray-200">
//                 <h2 className="text-lg font-medium text-gray-900">
//                   {conceptTitle} ({conceptPapers.length} papers)
//                 </h2>
//               </div>
//               <ul className="divide-y divide-gray-200">
//                 {conceptPapers.map((paper) => (
//                   <li key={paper.id} className="p-4 hover:bg-gray-50">
//                     <div className="flex items-center justify-between">
//                       <Link 
//                         href={`/manage/papers/${paper.slug}`} 
//                         className="flex-1"
//                       >
//                         <h3 className="text-lg font-medium">{paper.title}</h3>
//                         <div className="mt-1 flex items-center text-sm text-gray-500">
//                           <span>{paper.year}</span>
//                           <span className="mx-2">&bull;</span>
//                           <span>{paper.exam_type}</span>
//                           <span className="mx-2">&bull;</span>
//                           <span>{paper.questions.length} Questions</span>
//                         </div>
//                       </Link>
//                       <div className="flex gap-2">
//                         <Link href={`/manage/papers/${paper.slug}/edit`}>
//                           <Button variant="outline" size="sm">Edit</Button>
//                         </Link>
//                         <Button 
//                           variant="destructive" 
//                           size="sm"
//                           onClick={() => {
//                             if (confirm('Are you sure you want to delete this paper?')) {
//                               // Delete action
//                             }
//                           }}
//                         >
//                           Delete
//                         </Button>
//                       </div>
//                     </div>
//                   </li>
//                 ))}
//               </ul>
//             </div>
//           ))}
//         </div>
//       </div>
//     </div>
//   )
// }

// inertia/pages/manage/papers/index.vue
<!-- inertia/pages/manage/papers/index.vue -->
<script setup lang="ts">
import { Link } from '@inertiajs/vue3'
import type ConceptDto from '#dtos/concept'
import AdminLayout from '~/layouts/AdminLayout.vue'
import { FileText, Plus, ArrowLeft } from 'lucide-vue-next'

defineOptions({ layout: AdminLayout })

interface Props {
  concepts: ConceptDto[]
}

defineProps<Props>()

function goBack() {
  window.history.back()
}
</script>

<template>
  <AppHead title="Manage Past Papers" description="Manage examination papers" />
  
  <div class="container mx-auto px-4 py-6">
    <nav class="flex items-center gap-2 mb-6">
      <button @click="goBack" 
              class="flex items-center gap-2 text-muted-foreground hover:text-primary">
        <ArrowLeft class="h-4 w-4" />
        <span>Back</span>
      </button>
    </nav>

    <div class="space-y-8">
      <div v-for="concept in concepts" :key="concept.id" class="space-y-4">
        <div class="flex items-center justify-between">
          <h2 class="text-xl font-semibold">{{ concept.title }}</h2>
          <Link 
            :href="`/manage/papers/create/${concept.slug}`"
            class="flex items-center gap-2 text-sm px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90"
          >
            <Plus class="h-4 w-4" />
            Add Paper
          </Link>
        </div>

        <div v-if="concept.pastPapers?.length" 
             class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <Link
            v-for="paper in concept.pastPapers"
            :key="paper.id"
            :href="`/manage/papers/${paper.slug}`"
            class="p-4 rounded-lg border hover:border-primary transition-all"
          >
            <div class="flex items-start gap-3">
              <FileText class="h-5 w-5 text-primary" />
              <div>
                <h3 class="font-medium">{{ paper.title }}</h3>
                <p class="text-sm text-muted-foreground">{{ paper.year }}</p>
              </div>
            </div>
          </Link>
        </div>
        <p v-else class="text-sm text-muted-foreground">No papers added yet</p>
      </div>
    </div>
  </div>
</template>
