// inertia/pages/manage/papers/show.tsx
import { InferPageProps } from '@adonisjs/inertia/types'
import { Link } from '@inertiajs/react'
import { Button } from '~/components/ui/button'
import type { PapersController } from '../../../app/controllers/manage/papers_controller'

type Props = InferPageProps<typeof PapersController, 'show'>

export default function ShowPaper({ paper }: Props) {
  const mcqQuestions = paper.questions.filter(q => q.type === 'mcq')
  const saqQuestions = paper.questions.filter(q => q.type === 'saq')

  return (
    <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      {/* Paper Header with Actions */}
      <div className="mb-8 flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">{paper.title}</h1>
          <div className="mt-2 flex items-center text-sm text-gray-500">
            <span>{paper.concept.title}</span>
            <span className="mx-2">&bull;</span>
            <span>{paper.year}</span>
            <span className="mx-2">&bull;</span>
            <span>{paper.exam_type}</span>
          </div>
        </div>
        <div className="flex gap-2">
          <Link href={`/manage/papers/${paper.slug}/questions/new?type=mcq`}>
            <Button variant="outline">Add MCQ</Button>
          </Link>
          <Link href={`/manage/papers/${paper.slug}/questions/new?type=saq`}>
            <Button variant="outline">Add SAQ</Button>
          </Link>
        </div>
      </div>

      {/* MCQ Section */}
      {mcqQuestions.length > 0 && (
        <div className="mb-8">
          <h2 className="text-xl font-semibold mb-4">
            Multiple Choice Questions ({mcqQuestions.length})
          </h2>
          <div className="space-y-6">
            {mcqQuestions.map((question, index) => (
              <div key={question.id} className="group bg-white shadow rounded-lg p-6">
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-start">
                      <span className="font-medium mr-4">{index + 1}.</span>
                      <div>
                        <p className="text-gray-900 mb-4">{question.question_text}</p>
                        <div className="ml-4 space-y-2">
                          {question.choices?.map((choice) => (
                            <div
                              key={choice.id}
                              className={`p-3 rounded-lg ${
                                choice.is_correct ? 'bg-green-50 border border-green-200' : 'bg-gray-50'
                              }`}
                            >
                              <p className="text-gray-900">{choice.choice_text}</p>
                              {choice.is_correct && (
                                <p className="text-sm text-green-600 mt-1">{choice.explanation}</p>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="opacity-0 group-hover:opacity-100 transition-opacity flex gap-2">
                    <Link href={`/manage/papers/${paper.slug}/questions/${question.slug}/edit`}>
                      <Button variant="outline" size="sm">Edit</Button>
                    </Link>
                    <form 
                      action={`/manage/papers/${paper.slug}/questions/${question.slug}`} 
                      method="DELETE"
                    >
                      <Button 
                        variant="destructive" 
                        size="sm"
                        type="submit"
                        onClick={(e) => {
                          e.preventDefault()
                          if (confirm('Remove this question?')) {
                            e.currentTarget.form?.submit()
                          }
                        }}
                      >
                        Remove
                      </Button>
                    </form>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SAQ Section */}
      {saqQuestions.length > 0 && (
        <div>
          <h2 className="text-xl font-semibold mb-4">
            Structured Questions ({saqQuestions.length})
          </h2>
          <div className="space-y-6">
            {saqQuestions.map((question, index) => (
              <div key={question.id} className="group bg-white shadow rounded-lg p-6">
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-start">
                      <span className="font-medium mr-4">{index + 1}.</span>
                      <div>
                        <p className="text-gray-900 mb-4">{question.question_text}</p>
                        <div className="ml-4 space-y-4">
                          {question.parts?.map((part, partIndex) => (
                            <div key={part.id} className="border-l-2 border-gray-200 pl-4">
                              <p className="text-gray-900 font-medium mb-2">
                                {String.fromCharCode(97 + partIndex)}) {part.part_text}
                              </p>
                              <p className="text-sm text-gray-500">
                                Expected: {part.expected_answer}
                              </p>
                              <p className="text-sm text-gray-500">
                                Marks: {part.marks}
                              </p>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="opacity-0 group-hover:opacity-100 transition-opacity flex gap-2">
                    <Link href={`/manage/papers/${paper.slug}/questions/${question.slug}/edit`}>
                      <Button variant="outline" size="sm">Edit</Button>
                    </Link>
                    <form 
                      action={`/manage/papers/${paper.slug}/questions/${question.slug}`} 
                      method="DELETE"
                    >
                      <Button 
                        variant="destructive" 
                        size="sm"
                        type="submit"
                        onClick={(e) => {
                          e.preventDefault()
                          if (confirm('Remove this question?')) {
                            e.currentTarget.form?.submit()
                          }
                        }}
                      >
                        Remove
                      </Button>
                    </form>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// inertia/pages/manage/papers/show.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3'
import { computed, ref } from 'vue'
import type ConceptDto from '#dtos/concept'
import type PastPaperDto from '#dtos/past_paper'
import AdminLayout from '~/layouts/AdminLayout.vue'
import { FileText, Plus } from 'lucide-vue-next'
import CreatePaperDialog from '~/components/CreatePaperDialog.vue'

defineOptions({ layout: AdminLayout })

interface Props {
  concept: ConceptDto
  papers: PastPaperDto[]
}

const props = defineProps<Props>()
const isCreateDialogOpen = ref(false)

const breadcrumbItems = computed(() => [
  { label: 'Papers', href: '/papers' },
  { label: props.concept.title },
])
</script>

<template>
  <AppHead :title="`${concept.title} Papers`" :description="`Past papers for ${concept.title}`" />

  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-8">
    <!-- Header -->
    <div class="relative p-6 sm:p-8 bg-white/50 rounded-2xl border shadow-sm">
      <div
        class="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-primary via-primary/50 to-transparent"
      />

      <BreadcrumbTrail :items="breadcrumbItems" />

      <div class="flex items-start justify-between mt-4">
        <div class="flex items-start gap-4">
          <div class="p-3 rounded-xl bg-primary/5 border border-primary/10">
            <FileText class="h-6 w-6 text-primary" />
          </div>
          <div class="space-y-1">
            <h1 class="text-2xl font-bold text-foreground">{{ concept.title }}</h1>
            <p class="text-sm text-muted-foreground">Manage Past Papers</p>
          </div>
        </div>

        <Button @click="isCreateDialogOpen = true" class="flex items-center gap-2">
          <Plus class="h-4 w-4" />
          Add Paper
        </Button>
      </div>
    </div>

    <!-- Papers List -->
    <div v-if="papers.length" class="space-y-4">
      <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <Link
          v-for="paper in papers"
          :key="paper.id"
          :href="`/manage/papers/${concept.slug}/${paper.slug}`"
          class="group relative overflow-hidden rounded-xl bg-white p-5 border hover:border-primary/20 hover:shadow-md hover:-translate-y-0.5 transition-all duration-300"
        >
          <div class="relative space-y-3">
            <h3 class="text-lg font-semibold text-foreground">{{ paper.title }}</h3>
            <div class="flex items-center gap-3 text-sm">
              <span class="px-2 py-1 rounded-md bg-primary/10 text-primary font-medium">
                {{ paper.examType.toUpperCase() }}
              </span>
              <span class="text-muted-foreground">
                {{ paper.questions?.length ?? 0 }} questions
              </span>
              <span class="text-muted-foreground">{{ paper.year }}</span>
            </div>
          </div>
        </Link>
      </div>
    </div>

    <!-- Empty State -->
    <div v-else class="text-center p-8 bg-white rounded-xl border">
      <p class="text-muted-foreground">No papers added yet. Click "Add Paper" to create one.</p>
    </div>

    <!-- Create Paper Dialog -->
    <CreatePaperDialog v-model:open="isCreateDialogOpen" :concept="concept" />
  </div>
</template>
